module.exports = {
  env: {
    browser: true,
    es6: true,
    jquery: true
  },
  // extends: ['plugin:react/recommended'],
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
      impliedStrict: true
    }
  },
  plugins: ['react'],
  globals: {
    React: false,
    ReactDOM: false,
    $: false,
    jQuery: false,
    ReactBootstrap: false
  },
  rules: {
    'react/forbid-component-props': 1,
    'react/no-array-index-key': 1,
    'react/no-children-prop': 1,
    'react/no-danger': 1,
    'react/no-danger-with-children': 1,
    'react/no-deprecated': 1,
    'react/no-did-mount-set-state': 1,
    'react/no-did-update-set-state': 1,
    'react/no-direct-mutation-state': 1,
    'react/no-find-dom-node': 1,
    'react/no-is-mounted': 1,
    'react/no-multi-comp': 1,
    'react/no-redundant-should-component-update': 1,
    'react/no-render-return-value': 1,
    // 'react/no-typos': 1,
    'react/no-string-refs': 1,
    'react/no-unescaped-entities': 1,
    'react/no-unknown-property': 1,
    'react/no-unused-prop-types': 1,
    'react/no-will-update-set-state': 1,
    'react/prefer-es6-class': [1, 'always'],
    'react/react-in-jsx-scope': 1, // ?
    'react/require-render-return': 1,
    'react/self-closing-comp': 1,
    'react/sort-comp': 1,
    'react/style-prop-object': 1,
    'react/void-dom-elements-no-children': 1,

    'react/jsx-boolean-value': [1, 'always'],
    'react/jsx-closing-bracket-location': 1,
    'react/jsx-closing-tag-location': 1,
    'react/jsx-curly-spacing': [1, { when: 'always', children: true }],
    'react/jsx-equals-spacing': 1,
    'react/jsx-filename-extension': 1,
    'react/jsx-first-prop-new-line': 1,
    'react/jsx-indent': [1, 2],
    'react/jsx-indent-props': [1, 2],
    'react/jsx-key': 1,
    'react/jsx-max-props-per-line': [1, { when: 'multiline' }],
    'react/jsx-no-comment-textnodes': 1,
    'react/jsx-no-duplicate-props': 1,
    'react/jsx-no-target-blank': 1,
    'react/jsx-no-undef': 1, // ?
    'react/jsx-pascal-case': 1,
    'react/jsx-tag-spacing': 1,
    'react/jsx-uses-react': 1,
    'react/jsx-uses-vars': 1,
    'react/jsx-wrap-multilines': [1, { arrow: false, declaration: false, assignment: false }],



    'for-direction': 2,
    'getter-return': 2,
    'no-await-in-loop': 2,
    'no-compare-neg-zero': 2,
    'no-cond-assign': [1, 'except-parens'],
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-empty-character-class': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 1,
    'no-extra-semi': 1,
    'no-func-assign': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-obj-calls': 2,
    'no-prototype-builtins': 2,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-template-curly-in-string': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': 2,
    'use-isnan': 2,
    'valid-jsdoc': 1,
    'valid-typeof': 2,
    'accessor-pairs': 1,
    'array-callback-return': 2,
    'block-scoped-var': 1,
    'curly': 1,
    'default-case': 1,
    'dot-location': [1, 'property'],
    'dot-notation': 1,
    'eqeqeq': 2,
    'no-alert': 1,
    'no-caller': 1,
    'no-case-declarations': 1,
    'no-empty-function': 1,
    'no-empty-pattern': 2,
    'no-eq-null': 1,
    'no-eval': 1,
    'no-extend-native': 2,
    'no-extra-bind': 1,
    'no-extra-label': 1,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-global-assign': 2,
    'no-implicit-coercion': 1,
    'no-implicit-globals': 1,
    'no-implied-eval': 1,
    'no-iterator': 1,
    'no-lone-blocks': 1,
    'no-new': 1,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 1,
    'no-param-reassign': [1, { props: false }],
    'no-proto': 1,
    'no-redeclare': 1,
    'no-return-await': 1,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 1,
    'no-unused-expressions': [1, { allowShortCircuit: true, allowTernary: true }],
    'no-unused-labels': 1,
    'no-useless-call': 1,
    'no-useless-concat': 1,
    'no-useless-escape': 1,
    'no-useless-return': 1,
    'no-void': 1,
    'no-with': 1,
    'require-await': 2,
    'vars-on-top': 1,
    'wrap-iife': [1, 'any'],
    'yoda': [1, 'never', { onlyEquality: true }],
    'strict': [1, 'never'],
    'no-catch-shadow': 1,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-shadow-restricted-names': 1,
    'no-undef': 2,
    'no-use-before-define': 2,
    'constructor-super': 2,
    'no-class-assign': 2,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-duplicate-imports': [2, { includeExports: true }],
    'no-new-symbol': 2,
    'no-this-before-super': 2,
    'no-useless-computed-key': 1,
    'no-useless-constructor': 1,
    'no-useless-rename': 1,
    'prefer-numeric-literals': 1,
    'prefer-rest-params': 1,
    'prefer-spread': 1,
    'require-yield': 2,
    'rest-spread-spacing': 1,
    'yield-star-spacing': 1
  }
};
