let common = require('./.eslintrc.common.js');

common.rules = Object.assign({}, common.rules, {
  'no-multi-spaces': 1,
  'no-console': [1, { 'allow': ['warn', 'error'] }],
  'no-debugger': 1,
  'no-empty': 1,
  'one-var': [1, 'never'],
  'one-var-declaration-per-line': [1, "always"],
  'operator-linebreak': [1, "after"],
  'padded-blocks': [1, "never"],
  'space-unary-ops': 1,
  'generator-star-spacing': ["error", {"before": false, "after": true}],
  'no-unused-vars': 1,
  'array-bracket-spacing': [1, 'always'],
  'block-spacing': 1,
  'brace-style': [1, '1tbs', { allowSingleLine: true }],
  'camelcase': 1,
  'comma-spacing': 1,
  'comma-style': 1,
  'computed-property-spacing': 1,
  'consistent-this': [1, 'that'],
  'eol-last': 1,
  'func-call-spacing': 1,
  'func-name-matching': 1,
  'func-style': [1, 'expression', { allowArrowFunctions: true}],
  'indent': [1, 2, { SwitchCase: 1 }],
  'jsx-quotes': 1,
  'key-spacing': [1, { mode: 'strict' }],
  'keyword-spacing': 1,
  'no-inline-comments': 1,
  'new-cap': 1,
  'new-parens': 1,
  'no-lonely-if': 1,
  'no-mixed-spaces-and-tabs': 1,
  'no-multiple-empty-lines': [1, { max: 2, maxEOF: 0, maxBOF: 0 }],
  'no-negated-condition': 1,
  'no-trailing-spaces': 1,
  'no-unneeded-ternary': 1,
  'no-whitespace-before-property': 1,
  'object-curly-spacing': [1, 'always'],
  'operator-assignment': 1,
  'quote-props': [1, 'as-needed'],
  'quotes': [1, 'single', { 'avoidEscape': true }],
  'semi': [1, 'always'],
  'semi-spacing': 1,
  'semi-style': 1,
  'space-before-blocks': 1,
  'space-before-function-paren': [1, 'never'],
  'space-in-parens': 1,
  'space-infix-ops': 1,
  'switch-colon-spacing': 1,
  'template-tag-spacing': 1,
  'arrow-spacing': 1,
  'no-var': 1,
  'prefer-arrow-callback': 1,
  'object-shorthand': 1,
  'prefer-template': 1,
  'no-else-return': 1
});

module.exports = common;
